name: TESTJACK

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
      - test

jobs:
  test-jack:
    runs-on: ubuntu-latest
    steps:
      - name: testjack
        shell: bash
        run: echo $GITHUB_REF_PROTECTED